### ISSUE TITLE
Properly raise the right error/exception when training fails

### ISSUE THREAD

**Issue by inventormc** [ray-project/tune-sklearn#108]
When an error happens in _trainable, we don't explicitly raise errors; we rely on Ray Tune to log the error so it shows up in logging, and catch the TuneError that's raised. Looks like this is making errors hard to understand, especially when logging is off. 

#107 

For example:
```python
import numpy as np
from tune_sklearn import TuneGridSearchCV
from sklearn.linear_model import Ridge, SGDClassifier
parameter_grid = {"alpha": [1e-4, 1e-1, 1], "epsilon": [0.01, 0.1]}


X = np.array([[-1, -1], [-2, -1], [1, 1], [2, 1], [2, 1]])
y = np.array([1, 1, 2, 2, 2])


tune_search = TuneGridSearchCV(
    SGDClassifier(), parameter_grid, scoring="f1_micro", max_iters=20)
tune_search.fit(X, y)
```

```
/Users/rliaw/dev/tune-sklearn/tune_sklearn/tune_basesearch.py:391: UserWarning: max_iters is set > 1 but incremental/partial training is not enabled. To enable partial training, ensure the estimator has `partial_fit` or `warm_start` and set `early_stopping=True`. Automatically setting max_iters=1.
  category=UserWarning)
File descriptor limit 256 is too low for production servers and may result in connection errors. At least 8192 is recommended. --- Fix with 'ulimit -n 8192'
Trial _Trainable_929b0_00005: Error processing event.
Traceback (most recent call last):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 726, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 489, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/worker.py", line 1473, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::_Trainable.train() (pid=89931, ip=192.168.1.115)
  File "/Users/rliaw/miniconda3/lib/python3.7/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

ray::_Trainable.train() (pid=89931, ip=192.168.1.115)
  File "python/ray/_raylet.pyx", line 472, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 476, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 477, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 431, in ray._raylet.execute_task.function_executor
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/ray/tune/trainable.py", line 336, in train
    result = self.step()
  File "/Users/rliaw/dev/tune-sklearn/tune_sklearn/_trainable.py", line 106, in step
    return self._train()
  File "/Users/rliaw/dev/tune-sklearn/tune_sklearn/_trainable.py", line 247, in _train
    return_train_score=self.return_train_score,
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 236, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/joblib/parallel.py", line 819, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 231, in <genexpr>
    delayed(_fit_and_score)(
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 335, in split
    for train, test in super().split(X, y, groups):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 80, in split
    for test_index in self._iter_test_masks(X, y, groups):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 692, in _iter_test_masks
    test_folds = self._make_test_folds(X, y)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 663, in _make_test_folds
    % (self.n_splits))
ValueError: n_splits=5 cannot be greater than the number of members in each class.
```
Note that this does not actually *raise* the error but instead logs it.
Here is the sklearn version for reference:
```
(base) ➜  tune-sklearn git:(master) ✗ python _test.py
Traceback (most recent call last):
  File "_test.py", line 14, in <module>
    tune_search.fit(X, y)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 710, in fit
    self._run_search(evaluate_candidates)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 1151, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 689, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 335, in split
    for train, test in super().split(X, y, groups):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 80, in split
    for test_index in self._iter_test_masks(X, y, groups):
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 692, in _iter_test_masks
    test_folds = self._make_test_folds(X, y)
  File "/Users/rliaw/miniconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py", line 663, in _make_test_folds
    % (self.n_splits))
ValueError: n_splits=5 cannot be greater than the number of members in each class.

**Comment by amogkam** [comment]
Hi @inventormc @richardliaw I'm currently working on fixing this issue. I probably being naive here, but isn't a quick fix to not silently catch TuneErrors and raise it instead? Is there a reason this wasn't done initially? If it's still necessary to catch the exception we could log the error instead. 

I ran the example from #107 and this is the full stacktrace:
```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    score=grid_search.score(X_test,y_test)
  File "/Users/amog/dev/tune-sklearn/tune_sklearn/tune_basesearch.py", line 679, in score
    self._check_is_fitted(self._metric_name)
  File "/Users/amog/dev/tune-sklearn/tune_sklearn/tune_basesearch.py", line 336, in _check_is_fitted
    check_is_fitted(self)
  File "/Users/amog/dev/ray/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/Users/amog/dev/ray/lib/python3.7/site-packages/sklearn/utils/validation.py", line 1019, in check_is_fitted
    raise NotFittedError(msg % {'name': type(estimator).__name__})
sklearn.exceptions.NotFittedError: This TuneGridSearchCV instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.
```
But this error is misleading; the problem is actually that `fit` doesn't finish running since there are no GPUs (or Ray cannot identify the GPUs). If I raise the `TuneError` instead of silently catching it, here is the stack trace:
```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    grid_search.fit(X_train, y_train)
  File "/Users/amog/dev/tune-sklearn/tune_sklearn/tune_basesearch.py", line 651, in fit
    result = self._fit(X, y, groups, **fit_params)
  File "/Users/amog/dev/tune-sklearn/tune_sklearn/tune_basesearch.py", line 551, in _fit
    analysis = self._tune_run(config, resources_per_trial)
  File "/Users/amog/dev/tune-sklearn/tune_sklearn/tune_gridsearch.py", line 256, in _tune_run
    loggers=self.loggers)
  File "/Users/amog/dev/ray/lib/python3.7/site-packages/ray/tune/tune.py", line 412, in run
    runner.step()
  File "/Users/amog/dev/ray/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 572, in step
    self.trial_executor.on_no_available_trials(self)
  File "/Users/amog/dev/ray/lib/python3.7/site-packages/ray/tune/trial_executor.py", line 177, in on_no_available_trials
    "Insufficient cluster resources to launch trial: "
ray.tune.error.TuneError: Insufficient cluster resources to launch trial: trial requested 1 CPUs, 1 GPUs, but the cluster has only 16 CPUs, 0 GPUs, 5.47 GiB heap, 1.86 GiB objects (1.0 node:192.168.2.228). Pass `queue_trials=True` in ray.tune.run() or on the command line to queue trials until the cluster scales up or resources become available.
```
which is much better.

**Comment by amogkam** [comment]
This is the only change I'm making- https://github.com/ray-project/tune-sklearn/pull/130

**Comment by richardliaw** [comment]
@amogkam thanks - i've updated the issue with a repro script and a error message. You can check the native sklearn version for a more desirable error message.

**Comment by inventormc** [comment]
Hi @amogkam thanks for looking at this. I think there are certain cases where there is an underlying issue from sklearn, but raising the TuneError directly will mask this underlying error (see #48 ). We'd want an error like this ideally:

```
Traceback (most recent call last):
  File "/Users/michaelchau/git/test/issue.py", line 34, in <module>
    grid_result = grid.fit(X, y)
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 73, in inner_f
    return f(**kwargs)
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 736, in fit
    self._run_search(evaluate_candidates)
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 1188, in _run_search
    evaluate_candidates(ParameterGrid(self.param_grid))
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 715, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 520, in _fit_and_score
    estimator = estimator.set_params(**cloned_parameters)
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/keras/wrappers/scikit_learn.py", line 114, in set_params
    self.check_params(params)
  File "/Users/michaelchau/anaconda3/lib/python3.7/site-packages/keras/wrappers/scikit_learn.py", line 90, in check_params
    '{} is not a legal parameter'.format(params_name))
ValueError: kernel_initializer is not a legal parameter
```

This is why we chose to silently catch at first.
