### ISSUE TITLE
Getting numerous errors and warnings using LightGBM

### ISSUE THREAD

**Issue by rohan-gt** [ray-project/tune-sklearn#131]
I'm getting a lot of errors and warnings when I run the following code on Google Colab. One which even says performance will be worse if I use `early_stopping` with LightGBM. Is this expected? :

````python
!pip install -U hpbandster lightgbm hyperopt ConfigSpace
!pip install -U git+https://github.com/ray-project/tune-sklearn/

from tune_sklearn import TuneSearchCV

# Other imports
import scipy
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from lightgbm import LGBMClassifier

# Set training and validation sets
X, y = make_classification(n_samples=11000, n_features=1000, n_informative=50, n_redundant=0, n_classes=10, class_sep=2.5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1000)

# Note the use of tuples instead if non-random optimization is desired
param_dists = {
    'reg_alpha': (1e-4, 1e-1),
    'reg_lambda': (1e-2, 1e-1, 'log-uniform')
}

bohb_tune_search = TuneSearchCV(LGBMClassifier(n_jobs=-1),
    param_distributions=param_dists,
    n_trials=2,
    max_iters=10,
    search_optimization="bohb"
)

bohb_tune_search.fit(X_train, y_train)

hyperopt_tune_search = TuneSearchCV(LGBMClassifier(n_jobs=-1),
    param_distributions=param_dists,
    n_trials=2,
    early_stopping=True, # uses Async HyperBand if set to True
    max_iters=10,
    search_optimization="hyperopt"
)

hyperopt_tune_search.fit(X_train, y_train)
````

outputs the following:

````
/usr/local/lib/python3.6/dist-packages/tune_sklearn/tune_basesearch.py:391: UserWarning: max_iters is set > 1 but incremental/partial training is not enabled. To enable partial training, ensure the estimator has `partial_fit` or `warm_start` and set `early_stopping=True`. Automatically setting max_iters=1.
  category=UserWarning)
/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
save not implemented for Searcher. Skipping save.
(pid=2469) 
(pid=2469) 
(pid=2469) --------------------------------------------------------------------------------
(pid=2469) LokyProcess-1 failed with traceback: 
(pid=2469) --------------------------------------------------------------------------------
(pid=2469) Traceback (most recent call last):
(pid=2469)   File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
(pid=2469)     prep_data = pickle.load(from_parent)
(pid=2469) ValueError: unsupported pickle protocol: 5
(pid=2469) 
(pid=2469) 
(pid=2469) --------------------------------------------------------------------------------
(pid=2469) 
(pid=2469) 
(pid=2469) --------------------------------------------------------------------------------
(pid=2469) LokyProcess-2 failed with traceback: 
(pid=2469) --------------------------------------------------------------------------------
(pid=2469) Traceback (most recent call last):
(pid=2469)   File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
(pid=2469)     prep_data = pickle.load(from_parent)
(pid=2469) ValueError: unsupported pickle protocol: 5
(pid=2469) 
(pid=2469) 
(pid=2469) --------------------------------------------------------------------------------
(pid=2469) exception calling callback for <Future at 0x7f0504928d30 state=finished raised TerminatedWorkerError>
(pid=2469) Traceback (most recent call last):
(pid=2469)   File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
(pid=2469)     callback(self)
(pid=2469)   File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 366, in __call__
(pid=2469)     self.parallel.dispatch_next()
(pid=2469)   File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 799, in dispatch_next
(pid=2469)     if not self.dispatch_one_batch(self._original_iterator):
(pid=2469)   File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 866, in dispatch_one_batch
(pid=2469)     self._dispatch(tasks)
(pid=2469)   File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 784, in _dispatch
(pid=2469)     job = self._backend.apply_async(batch, callback=cb)
(pid=2469)   File "/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py", line 531, in apply_async
(pid=2469)     future = self._workers.submit(SafeFunction(func))
(pid=2469)   File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/reusable_executor.py", line 178, in submit
(pid=2469)     fn, *args, **kwargs)
(pid=2469)   File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py", line 1102, in submit
(pid=2469)     raise self._flags.broken
(pid=2469) joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.
(pid=2469) 
(pid=2469) The exit codes of the workers are {EXIT(1)}
Trial _Trainable_ce701470: Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py", line 488, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TerminatedWorkerError): ray::_Trainable.train() (pid=2469, ip=172.28.0.2)
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py", line 336, in train
    result = self.step()
  File "/usr/local/lib/python3.6/dist-packages/tune_sklearn/_trainable.py", line 106, in step
    return self._train()
  File "/usr/local/lib/python3.6/dist-packages/tune_sklearn/_trainable.py", line 247, in _train
    return_train_score=self.return_train_score,
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py", line 236, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/_base.py", line 625, in _invoke_callbacks
    callback(self)
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 366, in __call__
    self.parallel.dispatch_next()
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 799, in dispatch_next
    if not self.dispatch_one_batch(self._original_iterator):
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py", line 531, in apply_async
    future = self._workers.submit(SafeFunction(func))
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/reusable_executor.py", line 178, in submit
    fn, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/process_executor.py", line 1102, in submit
    raise self._flags.broken
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1)}
(pid=2470) 
(pid=2470) 
(pid=2470) --------------------------------------------------------------------------------
(pid=2470) LokyProcess-1 failed with traceback: 
(pid=2470) --------------------------------------------------------------------------------
(pid=2470) Traceback (most recent call last):
(pid=2470)   File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
(pid=2470)     prep_data = pickle.load(from_parent)
(pid=2470) ValueError: unsupported pickle protocol: 5
(pid=2470) 
(pid=2470) 
(pid=2470) --------------------------------------------------------------------------------
/usr/local/lib/python3.6/dist-packages/tune_sklearn/tune_basesearch.py:435: UserWarning: tune-sklearn implements incremental learning for lightgbm models following this: https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMModel.html#lightgbm.LGBMModel.fit This may negatively impact performance. To disable, set `early_stopping=False`.
  category=UserWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/base.py:197: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  FutureWarning)
TuneSearchCV(cv=None,
             early_stopping=<ray.tune.schedulers.async_hyperband.AsyncHyperBandScheduler object at 0x7fed453d8208>,
             error_score=nan,
             estimator=LGBMClassifier(boosting_type='gbdt', class_weight=None,
                                      colsample_bytree=1.0,
                                      importance_type='split',
                                      learning_rate=0.1, max_depth=-1,
                                      min_child_samples=20,
                                      min_child_weight=0.001,
                                      min_split_gain=0.0, n_estimator...
                      <class 'ray.tune.logger.JsonLogger'>],
             max_iters=10, n_jobs=-1, n_trials=None,
             param_distributions={'reg_alpha': (0.0001, 0.1),
                                  'reg_lambda': (0.01, 0.1, 'log-uniform')},
             pipeline_auto_early_stop=True, random_state=None, refit=True,
             return_train_score=False,
             scoring={'score': <function _passthrough_scorer at 0x7fed47e252f0>},
             search_optimization='hyperopt', sk_n_jobs=-1, use_gpu=False,
             verbose=0)
````

**Comment by Yard1** [comment]
Can you try with Lgbm n_jobs set to 1?

**Comment by rohan-gt** [comment]
@Yard1 Still giving the `UserWarning: tune-sklearn implements incremental learning for lightgbm models following this: https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMModel.html#lightgbm.LGBMModel.fit This may negatively impact performance. To disable, set early_stopping=False.` error and the following output:

````
/usr/local/lib/python3.6/dist-packages/tune_sklearn/tune_basesearch.py:391: UserWarning: max_iters is set > 1 but incremental/partial training is not enabled. To enable partial training, ensure the estimator has `partial_fit` or `warm_start` and set `early_stopping=True`. Automatically setting max_iters=1.
  category=UserWarning)
/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
save not implemented for Searcher. Skipping save.
(pid=330) 
(pid=330) 
(pid=330) --------------------------------------------------------------------------------
(pid=330) LokyProcess-2 failed with traceback: 
(pid=330) --------------------------------------------------------------------------------
(pid=330) Traceback (most recent call last):
(pid=330)   File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
(pid=330)     prep_data = pickle.load(from_parent)
(pid=330) ValueError: unsupported pickle protocol: 5
(pid=330) 
(pid=330) 
(pid=330) --------------------------------------------------------------------------------
(pid=331) 
(pid=331) 
(pid=331) --------------------------------------------------------------------------------
(pid=331) LokyProcess-2 failed with traceback: 
(pid=331) --------------------------------------------------------------------------------
(pid=331) Traceback (most recent call last):
(pid=331)   File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
(pid=331)     prep_data = pickle.load(from_parent)
(pid=331) ValueError: unsupported pickle protocol: 5
(pid=331) 
(pid=331) 
(pid=331) --------------------------------------------------------------------------------
(pid=330) 
(pid=330) 
(pid=330) --------------------------------------------------------------------------------
(pid=330) LokyProcess-1 failed with traceback: 
(pid=330) --------------------------------------------------------------------------------
(pid=330) Traceback (most recent call last):
(pid=330)   File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
(pid=330)     prep_data = pickle.load(from_parent)
(pid=330) ValueError: unsupported pickle protocol: 5
(pid=330) 
(pid=330) 
(pid=330) --------------------------------------------------------------------------------
(pid=331) 
(pid=331) 
(pid=331) --------------------------------------------------------------------------------
(pid=331) LokyProcess-1 failed with traceback: 
(pid=331) --------------------------------------------------------------------------------
(pid=331) Traceback (most recent call last):
(pid=331)   File "/usr/local/lib/python3.6/dist-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 197, in <module>
(pid=331)     prep_data = pickle.load(from_parent)
(pid=331) ValueError: unsupported pickle protocol: 5
(pid=331) 
(pid=331) 
(pid=331) --------------------------------------------------------------------------------
Trial _Trainable_eb993f80: Error processing event.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trial_runner.py", line 515, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/ray_trial_executor.py", line 488, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/usr/local/lib/python3.6/dist-packages/ray/worker.py", line 1428, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(TerminatedWorkerError): ray::_Trainable.train() (pid=330, ip=172.28.0.2)
  File "python/ray/_raylet.pyx", line 484, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 438, in ray._raylet.execute_task.function_executor
  File "/usr/local/lib/python3.6/dist-packages/ray/tune/trainable.py", line 336, in train
    result = self.step()
  File "/usr/local/lib/python3.6/dist-packages/tune_sklearn/_trainable.py", line 106, in step
    return self._train()
  File "/usr/local/lib/python3.6/dist-packages/tune_sklearn/_trainable.py", line 247, in _train
    return_train_score=self.return_train_score,
  File "/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_validation.py", line 236, in cross_validate
    for train, test in cv.split(X, y, groups))
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 1061, in __call__
    self.retrieve()
  File "/usr/local/lib/python3.6/dist-packages/joblib/parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/usr/local/lib/python3.6/dist-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {EXIT(1), EXIT(1)}
/usr/local/lib/python3.6/dist-packages/tune_sklearn/tune_basesearch.py:435: UserWarning: tune-sklearn implements incremental learning for lightgbm models following this: https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMModel.html#lightgbm.LGBMModel.fit This may negatively impact performance. To disable, set `early_stopping=False`.
  category=UserWarning)
````

**Comment by Yard1** [comment]
I ran the code you posted and couldn't replicate the exception. The warnings will be improved.

**Comment by richardliaw** [comment]
This is related to this error: https://github.com/ray-project/ray/issues/11547.

A fix should be:

```

# Other imports
import scipy
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from lightgbm import LGBMClassifier

# Move tune_sklearn later
from tune_sklearn import TuneSearchCV
```

**Comment by rohan-gt** [comment]
@Yard1 did you try running it on Google Colab?

**Comment by richardliaw** [comment]
@rohan-gt did the fix work?

**Comment by rohan-gt** [comment]
@richardliaw yes now it doesn't show as many warnings. So the warnings only pop up if the order of imports changes? 

The performance warning for using early stopping with lightgbm still shows though. Isn't early stopping supposed to speed up the algorithm?

Also why not keep HyperbandForBOHB as the default scheduler for BOHB? Why throw the warning at all?

**Comment by richardliaw** [comment]
Early stopping requires "incremental training" which is often slower than the standard mode of training. 

Can you create a new issue for the BOHB default? I think that's a great suggestion.

I'll close this issue now since we have a new release!
