### ISSUE TITLE
TuneSearchCV -> TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by arainboldt** [ray-project/tune-sklearn#208]
Trying out a simple example using TuneSearchCV with LGBMClassifier and it fails on start.

Environment:

Python 3.8.3
tune-sklearn 0.3.0
ray 1.3.0
macos mojave 10.14.6

Code:

```

from ray.tune.sklearn import TuneSearchCV

from lightgbm import LGBMClassifier

lgmb_param_dists = dict(

                boosting_type=['gbdt','dart','rf'],
                num_leaves=(10,500),
                max_depth=(1,10),
                learning_rate=(1e-10,.1),
                n_estimators=(10,200),
                subsample=(0.3,.8),
                subsample_freq=(3,7),
                colsample_bytree=(.3,.7),
                reg_alpha=(0,1),
                reg_lambda=(0,1),
    
                ),


def param_search(estimator,param_space,X,y,scorer='roc_auc',n_iters=50,n_folds=5,search_method='bohb',model_name=None,
                 ):
    
    if model_name is None:
        model_name = estimator.__class__.__name__
    


    param_model = TuneSearchCV(estimator, 
                      param_space, 
                      early_stopping=True, 
                      n_trials=10, 
                      scoring=scorer, 
                      n_jobs=None, 
                      refit=True, 
                      cv=n_folds, 
                      verbose=0, 
                      random_state=42, 
                      error_score=np.nan, 
                      return_train_score=False, 
                      local_dir='~/model_logs', 
                      name=name, 
                      max_iters=n_iters, 
                      search_optimization=search_method, 
                      loggers=['csv'], 
                      pipeline_auto_early_stop=True, 
                      sk_n_jobs=-2, 
                      mode='max')

    
    param_model.fit(X,y)
    
    print(f'Best Model Score: {param_model.score(X,y)}')
    
    return model_class(**param_model.best_params_)
```

Traceback:

```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-138-9a17be04018b> in <module>
     35 base_est = LGBMClassifier(class_weight='balanced',random_state=42,n_jobs=-2,silent=True,objective='multiclass')
     36 
---> 37 model = param_search(base_est,lgmb_param_dists,train_data,y)
     38 full_glb_preds = pd.DataFrame(model.predict_proba(pred_data),index=pred_data.index )\
     39                              .rename(codes_to_labels,axis=1)

<ipython-input-137-a31569cdb18f> in param_search(estimator, param_space, X, y, scorer, n_iters, n_folds, search_method, model_name)
     29 
     30 
---> 31     param_model = TuneSearchCV(estimator, 
     32                       param_space,
     33                       early_stopping=True,

TypeError: 'NoneType' object is not callable

```

**Comment by arainboldt** [comment]
Seems that others are having the issue as well. I found this kaggle kernel while searching for the error.

[https://www.kaggle.com/sivasaiyadav8143/10-hyperparameter-optimization-frameworks](url)

**Comment by Yard1** [comment]
That import doesn't look right. Can you try `from tune_sklearn import TuneSearchCV` instead of `from ray.tune.sklearn import TuneSearchCV`?

**Comment by SC12138** [comment]
I met the same issue. And `from tune_sklearn import TuneSearchCV` returns as follow:

`>>> from tune_sklearn import TuneSearchCV
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tune_sklearn/__init__.py", line 2, in <module>
    from tune_sklearn.tune_search import TuneSearchCV
  File "/home/ubuntu/.local/lib/python3.8/site-packages/tune_sklearn/tune_search.py", line 17, in <module>
    from ray.tune.suggest.bohb import TuneBOHB
  File "/home/ubuntu/.local/lib/python3.8/site-packages/ray/tune/suggest/bohb.py", line 8, in <module>
    import ConfigSpace
ModuleNotFoundError: No module named 'ConfigSpace'`

**Comment by richardliaw** [comment]
Hmm, seems like we need to provide a better error message on the Tune side.
