### ISSUE TITLE
Error messages when running random forest example

### ISSUE THREAD

**Issue by MislavSag** [ray-project/tune-sklearn#50]
I have just tried to run your example script for random forest (https://github.com/ray-project/tune-sklearn/blob/master/examples/random_forest.py).

When I run it, I am getting following errors/warnings:
```
WARNING:ray.worker:The dashboard on node DESKTOP-KBV1GE9 failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ray\dashboard/dashboard.py", line 960, in <module>
    metrics_export_address=metrics_export_address)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ray\dashboard/dashboard.py", line 513, in __init__
    build_dir = setup_static_dir(self.app)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ray\dashboard/dashboard.py", line 414, in setup_static_dir
    "&& npm run build)", build_dir)
FileNotFoundError: [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/dashboard/client && npm ci && npm run build): 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\dashboard\\client/build'

ERROR:ray.tune.tune:Trial Runner checkpointing failed.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\ray\tune\tune.py", line 332, in run
    runner.checkpoint(force=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ray\tune\trial_runner.py", line 279, in checkpoint
    os.rename(tmp_file_name, self.checkpoint_file)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Mislav\\ray_results\\_Trainable\\.tmp_checkpoint' -> 'C:\\Users\\Mislav\\ray_results\\_Trainable\\experiment_state-2020-07-20_19-42-07.json'
0.9555555555555556
```
It returns the result, but I am not sure what those error messages mean?

**Comment by richardliaw** [comment]
I think those are harmless errors, but we should do a better job of hiding them. You can hide them in your application for now by calling the following at the top of your script:

```
import logging
ray_logger = logging.getLogger("ray")
ray_logger.setLevel("CRITICAL")

**Comment by MislavSag** [comment]
Ok, than. If they are harmless, it can be closed.
