### ISSUE TITLE
TuneGridSearchCV.fit(X, Y) would not run

### ISSUE THREAD

**Issue by 1fornothin** [ray-project/tune-sklearn#64]
Hi I am using TuneGridSearchCV.fit below as example and are getting the following error. 

X, y = make_classification(n_samples=11000, n_features=1000, n_informative=50, 
                           n_redundant=0, n_classes=10, class_sep=2.5)

TuneGridSearchCV.fit(X, y)

TuneGridSearchCV.fit(X, y)
Traceback (most recent call last):

  File "<ipython-input-11-b4425021dbf1>", line 1, in <module>
    TuneGridSearchCV.fit(X, y)

  File "C:\Users\myusername\AppData\Local\Programs\anaconda3\lib\site-packages\tune_sklearn\tune_basesearch.py", line 385, in fit
    result = self._fit(X, y, groups, **fit_params)

AttributeError: 'numpy.ndarray' object has no attribute '_fit'

**Comment by inventormc** [comment]
Hi thanks for reaching out! Did you call `fit` as you showed in your short example above? If so, you need to instantiate TuneGridSearchCV to call fit, not just use the name of the class. Here's what that would look like:

```
clf = SGDClassifier()
parameter_grid = {"alpha": (1e-4, 1), "epsilon": (0.01, 0.1)}

tune_search = TuneGridSearchCV(
    clf,
    parameter_grid,
    early_stopping=True)
tune_search.fit(x_train, y_train)
```

Check out other examples [here](https://github.com/ray-project/tune-sklearn/tree/master/examples) for reference.

**Comment by 1fornothin** [comment]
Yes sorry misread... I am now getting the following error when I run the example, what do the below mean?

Log sync requires rsync to be installed.
Log sync requires rsync to be installed.
Log sync requires rsync to be installed.
Log sync requires rsync to be installed.
Log sync requires rsync to be installed.
Log sync requires rsync to be installed.
The dashboard on node L2ZXC01L0 failed with the following error:
Traceback (most recent call last):

  File "C:\Users\l2zxc01\AppData\username\Programs\anaconda3\lib\site-packages\ray\dashboard/dashboard.py", line 960, in <module>
    metrics_export_address=metrics_export_address)
  File "C:\Users\username\AppData\Local\Programs\anaconda3\lib\site-packages\ray\dashboard/dashboard.py", line 513, in __init__
    build_dir = setup_static_dir(self.app)
  File "C:\Users\username\AppData\Local\Programs\anaconda3\lib\site-packages\ray\dashboard/dashboard.py", line 414, in setup_static_dir
    "&& npm run build)", build_dir)
FileNotFoundError: [Errno 2] Dashboard build directory not found. If installing from source, please follow the additional steps required to build the dashboard(cd python/ray/dashboard/client && npm ci && npm run build): 'C:\\Users\\username\\AppData\\Local\\Programs\\anaconda3\\lib\\site-packages\\ray\\dashboard\\client/build'

**Comment by inventormc** [comment]
This might be a windows issue. Can you post the script you ran as well?

**Comment by 1fornothin** [comment]
yes, I used the example posted on github.

from tune_sklearn import TuneGridSearchCV

# Other imports
import os
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier

# Set training and validation sets
X, y = make_classification(n_samples=11000, n_features=1000, n_informative=50, n_redundant=0, n_classes=10, class_sep=2.5)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1000)

# Example parameters to tune from SGDClassifier
parameters = {
    'alpha': [1e-4, 1e-1, 1],
    'epsilon':[0.01, 0.1]
}

tune_search = TuneGridSearchCV(
    SGDClassifier(),
    parameters,
    early_stopping="MedianStoppingRule",
    max_iters=10
)

import time # Just to compare fit times
start = time.time()
tune_search.fit(X_train, y_train)
end = time.time()
print("Tune Fit Time:", end - start)
pred = tune_search.predict(X_test)
accuracy = np.count_nonzero(np.array(pred) == np.array(y_test)) / len(pred)
print("Tune Accuracy:", accuracy)

**Comment by richardliaw** [comment]
The `FileNotFoundError: [Errno 2] Dashboard build directory not found.` is non-fatal. I understand that the script you posted outputs a "Dashboard" message, but does it run until completion? Or are there other failure messages that arise?

**Comment by 1fornothin** [comment]
It looks like it is running when I set n_job to a low number, but when I increase it to around 5 cpu I get the following error: why is that happening?

tune_search.fit(data.X_train.values, np.ravel(data.y_train))
Log sync requires rsync to be installed.
Trial _Trainable_3dba8_00000: Unexpected error starting runner.
Traceback (most recent call last):
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 294, in start_trial
    self._start_trial(trial, checkpoint, train=train)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 233, in _start_trial
    runner = self._setup_remote_runner(trial, reuse_allowed)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 185, in _setup_remote_runner
    return cls.remote(**kwargs)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\actor.py", line 379, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\actor.py", line 572, in _remote
    extension_data=str(actor_method_cpu))
  File "python\ray\_raylet.pyx", line 911, in ray._raylet.CoreWorker.create_actor
  File "python\ray\_raylet.pyx", line 912, in ray._raylet.CoreWorker.create_actor
  File "python\ray\_raylet.pyx", line 253, in ray._raylet.prepare_resources
ValueError: Resource quantities >1 must be whole numbers.
The `start_trial` operation took 2.0664517879486084 seconds to complete, which may be a performance bottleneck.
Log sync requires rsync to be installed.
Trial _Trainable_3dba8_00001: Unexpected error starting runner.
Traceback (most recent call last):
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 294, in start_trial
    self._start_trial(trial, checkpoint, train=train)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 233, in _start_trial
    runner = self._setup_remote_runner(trial, reuse_allowed)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 185, in _setup_remote_runner
    return cls.remote(**kwargs)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\actor.py", line 379, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\actor.py", line 572, in _remote
    extension_data=str(actor_method_cpu))
  File "python\ray\_raylet.pyx", line 911, in ray._raylet.CoreWorker.create_actor
  File "python\ray\_raylet.pyx", line 912, in ray._raylet.CoreWorker.create_actor
  File "python\ray\_raylet.pyx", line 253, in ray._raylet.prepare_resources
ValueError: Resource quantities >1 must be whole numbers.
The `start_trial` operation took 2.076355457305908 seconds to complete, which may be a performance bottleneck.
Log sync requires rsync to be installed.
Trial _Trainable_3dba8_00002: Unexpected error starting runner.
Traceback (most recent call last):
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 294, in start_trial
    self._start_trial(trial, checkpoint, train=train)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 233, in _start_trial
    runner = self._setup_remote_runner(trial, reuse_allowed)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 185, in _setup_remote_runner
    return cls.remote(**kwargs)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\actor.py", line 379, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\actor.py", line 572, in _remote
    extension_data=str(actor_method_cpu))
  File "python\ray\_raylet.pyx", line 911, in ray._raylet.CoreWorker.create_actor
  File "python\ray\_raylet.pyx", line 912, in ray._raylet.CoreWorker.create_actor
  File "python\ray\_raylet.pyx", line 253, in ray._raylet.prepare_resources
ValueError: Resource quantities >1 must be whole numbers.
The `start_trial` operation took 2.0738601684570312 seconds to complete, which may be a performance bottleneck.
Log sync requires rsync to be installed.
Trial _Trainable_3dba8_00003: Unexpected error starting runner.
Traceback (most recent call last):
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 294, in start_trial
    self._start_trial(trial, checkpoint, train=train)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 233, in _start_trial
    runner = self._setup_remote_runner(trial, reuse_allowed)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 185, in _setup_remote_runner
    return cls.remote(**kwargs)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\actor.py", line 379, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\actor.py", line 572, in _remote
    extension_data=str(actor_method_cpu))
  File "python\ray\_raylet.pyx", line 911, in ray._raylet.CoreWorker.create_actor
  File "python\ray\_raylet.pyx", line 912, in ray._raylet.CoreWorker.create_actor
  File "python\ray\_raylet.pyx", line 253, in ray._raylet.prepare_resources
ValueError: Resource quantities >1 must be whole numbers.
The `start_trial` operation took 2.0545217990875244 seconds to complete, which may be a performance bottleneck.
Log sync requires rsync to be installed.
Trial _Trainable_3dba8_00004: Unexpected error starting runner.
Traceback (most recent call last):
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 294, in start_trial
    self._start_trial(trial, checkpoint, train=train)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 233, in _start_trial
    runner = self._setup_remote_runner(trial, reuse_allowed)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\tune\ray_trial_executor.py", line 185, in _setup_remote_runner
    return cls.remote(**kwargs)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\actor.py", line 379, in remote
    return self._remote(args=args, kwargs=kwargs)
  File "C:\Users\l2zxc01\AppData\Local\Programs\anaconda3\lib\site-packages\ray\actor.py", line 572, in _remote
    extension_data=str(actor_method_cpu))
  File "python\ray\_raylet.pyx", line 911, in ray._raylet.CoreWorker.create_actor
  File "python\ray\_raylet.pyx", line 912, in ray._raylet.CoreWorker.create_actor
  File "python\ray\_raylet.pyx", line 253, in ray._raylet.prepare_resources
ValueError: Resource quantities >1 must be whole numbers.
The `start_trial` operation took 2.0704779624938965 seconds to complete, which may be a performance bottleneck.

**Comment by richardliaw** [comment]
Ah, I think this is just a bug on our end. Can you try setting it to an integer factor of your total CPU? We will fix this in the upcoming week.
